/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame3.java
 *
 * Created on Nov 22, 2018, 12:00:35 AM
 */
package jkl;
import static jkl.koi.any;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ahps229
 */
public class NewJFrame3 extends javax.swing.JFrame {

    /** Creates new form NewJFrame3 */
    public NewJFrame3() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        records = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        oo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        records.setBackground(new java.awt.Color(0, 0, 0));
        records.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        records.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        records.setForeground(new java.awt.Color(255, 255, 255));
        records.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "senders name", "recivers name", "message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(records);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 375, 290));

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        jButton3.setText("log out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 80, 30));

        oo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        oo.setText("SHOW RECORDS");
        oo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ooActionPerformed(evt);
            }
        });
        getContentPane().add(oo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("MESSAGE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 120, 20));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Send to....");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 110, 30));
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 130, -1));

        t1.setColumns(20);
        t1.setRows(5);
        jScrollPane2.setViewportView(t1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton2.setText("SEND");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jkl/videoblocks-4k-green-particle-smoothy-flow-opacity-to-change-black-screen-background-to-green-screen-background-concept-for-changing-to-advertisement-by-insert-another-business-video_buh2nb1tg_thumbnai.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 660, 330));

        setSize(new java.awt.Dimension(557, 322));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ooActionPerformed
       
        String un=any;
        records.setModel(new DefaultTableModel(null,new String[]{"sendername","receivername","message  "})); 
        
        try {
           
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/ishan","root","123");
            
            
            Statement stmt=con.createStatement();
            DefaultTableModel any=(DefaultTableModel) records.getModel() ;
            String q="select * from "+un+";";
            ResultSet rs = stmt.executeQuery(q);
           
            while (rs.next())
            
            {
                
                String sendername=rs.getString("sendersnm");
                String receivername=rs.getString("receiversnm");
                String message=rs.getString("matter");
       
          Object data[]={sendername,receivername,message};
                any.addRow(data);}
        
            
            
        }
        
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
       
        }
        
        
        // TODO add your handling code here:
}//GEN-LAST:event_ooActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        String a=t1.getText();
        String un=any;
        String w=p1.getText();
        String m=null;
       
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost/ishan","root","123");
            Statement stmt=con.createStatement();
             String v="select * from "+w+";";
            ResultSet cs = stmt.executeQuery(v);
              
         
             m="insert into "+w+" values('"+any+"','"+w+"','"+a+"');";
            String q="insert into "+un+" values('"+any+"','"+w+"','"+a+"');";
            
            int rs = stmt.executeUpdate(q);
            int ps = stmt.executeUpdate(m);
            JOptionPane.showMessageDialog(null,"message send");
            
              
           
        
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"User not found");
        }
        
        
        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose(); new INTRODUC().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton oo;
    private javax.swing.JTextField p1;
    private javax.swing.JTable records;
    private javax.swing.JTextArea t1;
    // End of variables declaration//GEN-END:variables
}
